name: Deploy to EC2

on:
  push:
    branches:
      - main # or the branch you want to trigger the action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/comp7940parkinglot:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: -----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAudakSWPHS0WtRsoztRc+x3uBY5rcHF567FVXtrUlaJUGDCkF\nndASPFmZQfb58Re5+5qku3PuAHngq6xnlhVr4vmJMC8TuKiGXgfexcseDXWjhAVc\nc8IutKb5E9j9sBzlrEX55DBNH7xHdN8ftAVUi01D56GwafkWsnuDthG4XPdnLaYI\nKVuepSqthK3Hht1Ql+aEE+vZDfCA52/KzGH18R0RDTnrcBNnM0WXg9DirdZD5lSN\nYhHwHvKYEFdUXRl5m+LEQY1TYSl6+T0UBnccgcT946iREB16xw33Q6MWLU3hxzNO\nuKMacM986KnANH73W7xoyTCv6uU+wzq9/IHUYQIDAQABAoIBAHgiV2XSCL2SN2ex\nwydn9X+DSauYKn50XUZ2DRPhmmM3IwetZSIVphQ5X6eS/xRp4CLUX3WGhe7s2t5f\nvz74bhv2cEcjx73xw5r5v3thyPWufJwV0yRJ/WNvJUk9VxIIPDjXq6llyBWh4xec\nPaRkZbj/o8wTbDW1foS27/g9EE+XzRm7AiDrShw2+32X5ksCDXZX92IKjQ7wCJ08\nTp0Kzg+qa+a3rnocZE5fLep95ZToaqvPWV/XLSOKDeKCNSfC7+XRKOZ2xFoxZoWB\nc/I1hRISxLusYYoE0/Zj9PFWypZvvPsV+bX7rPlfs9ciX1FpCptpKufNdzgSBeNn\nBgQcDnkCgYEA6Hf4tddJIJomDVChwcWGaw1ca8z+k4aMSaVlFxITOVztItZkLXM4\ncyYTjmhYMXSmyxTu2sDn9UI64YbZY7P6MJs71L7zhEFVrrYz9m+FE0LaxGGKipnO\nvYGS9mmKs2EV+gzt+Q1gutS7jMpt8mgMrQuS7iQessqrETGpc9DVFm8CgYEAzKZU\nBnA0PXBSRlWlu/52z4s1I0ZGTvVZBxdHaCB9uqqjd6Cw/vukOqww4sBA95clyD2C\n0NwD8SdJt6VAQmq88CwLJDQodRidLkRdeSxMEBai1SyxT9dApe12+I2+KJaSBAOV\n8y/vE6XpPu62pZe0YkmQnKie/gXi3OpsmknTqi8CgYEA4ZSBgJsPOBa9NBB5VtoA\n7OLDO0xqAOgAO/rGFNQSWYimCDc4cK4tKffZ5Ee2xQ7oR4rhmN62d9Uz4+MCEnD0\nJ7SLI4/EKCNqLKZb2BgxbxZhyUzJrmNALb6NyJVz5Ushk0p2pkVoBwQllqJcfGyh\nWE4x3uqn62ElDQM+5sbP7/sCgYAeavaAQnsxSpmgBKjuqWLldE6AoLhgkg0ahbZC\nXtnxPd2wMT09mQ+O/PsDKQo/AsNF4QapnpojZPCLEE/dz1mn5RP+3JXK2c67CsRN\n92yS05p+TvdH47mjMAmH5iGGjOLFH/dQvyYs6HMjvH1/XW4dUcvhzRpcrWlL5rgf\nsqt4VwKBgHmkfy9VSaSnFQG9EXcq7f3AydPx+pghzZ9SoYt74WEdccB3XQ/Y8pbH\n/IhC/pDKPv/26spBdXFvYi6M6fT5dqSKjK26bSNtVOAAHlf5eul0M0sSpx6RhNRm\nwo6UzIG39vI0VHozOC3SMjN45N+UK0FDzbOId8SKfukisiHuYmur\n-----END RSA PRIVATE KEY-----\n
        script: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/comp7940parkinglot:latest
          sudo docker stop chatbot7940 || true
          sudo docker rm chatbot7940 || true
          sudo docker run -d --name chatbot7940 -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/comp7940parkinglot:latest
